import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Icon, Button, PageHeader, StatusBadge } from '../components/ui'
import { dashboardOrders, products, customers, clarificationCards, deliveryColumns } from '../data/mockData'

function SearchToolbar({ placeholder = 'Search by name, order ID or phone', filters = [] }) {
  return <div className="toolbar"><div className="search-box"><span className="icon"><Icon name="search" size={15}/></span><input className="input" placeholder={placeholder}/></div>{filters.map(filter => <select className="select" key={filter} defaultValue="All"><option>All {filter}</option><option>Active {filter}</option><option>Needs attention</option></select>)}<Button variant="ghost" icon="filter">Filters</Button></div>
}

function OrdersPage() {
  const [filter, setFilter] = useState('All')
  const navigate = useNavigate()
  const visible = filter === 'All' ? dashboardOrders : dashboardOrders.filter(order => order.status.toLowerCase().includes(filter.toLowerCase().replace(' ', '')) || (filter === 'Clarification required' && order.status.includes('clarification')))
  return <><PageHeader eyebrow="Order operations" title="Orders" subtitle="Track every order from first message to doorstep." actions={<Button icon="plus" onClick={() => navigate('/ai-desk')}>New order</Button>}/><div className="page-tabs">{['All','Pending','Clarification required','Confirmed','Packing','Out for delivery','Delivered'].map(item => <button className={`page-tab ${filter===item?'active':''}`} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><SearchToolbar placeholder="Search by order ID, customer or product" filters={['Source']}/><section className="card data-card"><div className="table-wrap"><table className="orders-table"><thead><tr><th>Order</th><th>Customer</th><th>Source</th><th>Items</th><th>Amount</th><th>Delivery</th><th>Status</th><th>Action</th></tr></thead><tbody>{visible.map(order => <tr key={order.id}><td><span className="order-id">{order.id}</span><div style={{fontSize:10,color:'var(--muted)',marginTop:4}}>Today, 10:42 AM</div></td><td><div className="customer-cell"><strong>{order.customer}</strong><span>{order.phone}</span></div></td><td>{order.source}</td><td>{order.items}</td><td><strong>{order.amount}</strong></td><td>{order.delivery}</td><td><StatusBadge status={order.status}/></td><td><Button variant="ghost">View</Button></td></tr>)}</tbody></table></div></section></>
}

function ClarificationsPage() {
  return <><PageHeader eyebrow="Human-in-the-loop" title="Pending clarifications" subtitle="Give customers a clear answer when their order needs one more detail." actions={<Button variant="ghost" icon="check">Resolve all safe matches</Button>}/><div className="grid clarification-grid">{clarificationCards.map(card => <section className="card clarification-card" key={card.id}><div className="attention-head"><div className="attention-customer"><div className="avatar">{card.customer.split(' ').map(word=>word[0]).join('')}</div><div><h3>{card.customer}</h3><p>{card.id} · WhatsApp</p></div></div><span className="status pending">Needs reply</span></div><div className="quote">“{card.phrase}”</div><div className="issue"><strong>AI detected:</strong> {card.issue}</div><div className="analysis-section-label" style={{marginTop:14}}>Candidate products</div><div className="candidate-list">{card.candidates.map(candidate => <span className="candidate" key={candidate}>{candidate}</span>)}</div><div className="analysis-section-label">Suggested WhatsApp reply</div><div className="reply-box">{card.reply}</div><div className="card-actions"><Button variant="ai" icon="send">Send WhatsApp</Button><Button variant="ghost">Resolve manually</Button></div></section>)}</div></>
}

function ProductsPage({ inventory = false }) {
  const rows = inventory ? products.filter(product => product.state !== 'Healthy') : products
  return <><PageHeader eyebrow={inventory ? 'Store health' : 'Catalogue management'} title={inventory ? 'Inventory' : 'Products'} subtitle={inventory ? 'Know what is ready to sell before the next order arrives.' : 'Your AI uses this catalogue to match casual customer language.'} actions={!inventory && <Button icon="plus">Add product</Button>}/><div className="metric-row"><div className="card metric"><span>{inventory ? 'Healthy stock' : 'Active products'}</span><strong>{inventory ? '23' : '86'}</strong><small>+4 this month</small></div><div className="card metric"><span>Low stock</span><strong>12</strong><small style={{color:'#a57b32'}}>Needs a refill</small></div><div className="card metric"><span>Out of stock</span><strong>3</strong><small style={{color:'#ad6565'}}>Review today</small></div><div className="card metric"><span>Last synced</span><strong style={{fontSize:18}}>2 min ago</strong><small>Catalogue is current</small></div></div><SearchToolbar placeholder={inventory ? 'Search inventory' : 'Search products by name or brand'} filters={['Brand','Category','Stock']}/><section className="card data-card"><div className="table-wrap"><table className="orders-table"><thead><tr><th>Product</th><th>Brand</th><th>Category</th><th>Pack size</th><th>Price</th><th>{inventory ? 'Availability' : 'Stock'}</th><th>State</th><th></th></tr></thead><tbody>{rows.map(product => <tr key={`${product.name}-${product.pack}`}><td><div className="mini-product"><div className="product-thumb green">{product.name[0]}</div><div><strong>{product.name}</strong><span>Updated 2 min ago</span></div></div></td><td>{product.brand}</td><td>{product.category}</td><td>{product.pack}</td><td><strong>{product.price}</strong></td><td><strong>{product.stock} units</strong><div className="progress" style={{width:80}}><i className={product.stock===0?'low':product.state!=='Healthy'?'warning':''} style={{width:`${Math.min(product.stock / product.threshold * 100, 100)}%`}}/></div></td><td><StatusBadge status={product.state}/></td><td><button className="icon-btn"><Icon name="more" size={15}/></button></td></tr>)}</tbody></table></div></section></>
}

function CustomersPage() {
  return <><PageHeader eyebrow="Customer relationships" title="Customers" subtitle="A lightweight memory for repeat orders and preferences." actions={<Button icon="plus">Add customer</Button>}/><SearchToolbar placeholder="Search name or phone number" filters={['Orders']}/><section className="card data-card"><div className="table-wrap"><table className="orders-table"><thead><tr><th>Customer</th><th>Orders</th><th>Total spend</th><th>Last order</th><th>Usually buys</th><th></th></tr></thead><tbody>{customers.map(customer => <tr key={customer.phone}><td><div className="customer-cell"><strong>{customer.name}</strong><span>{customer.phone}</span></div></td><td>{customer.orders}</td><td><strong>{customer.spend}</strong></td><td>{customer.last}</td><td>{customer.favourite}</td><td><button className="icon-btn"><Icon name="chevron" size={15}/></button></td></tr>)}</tbody></table></div></section></>
}

function DeliveriesPage() {
  return <><PageHeader eyebrow="Last-mile workspace" title="Deliveries" subtitle="A simple view of what needs to move next." actions={<Button variant="ghost" icon="truck">Delivery settings</Button>}/><div className="metric-row"><div className="card metric"><span>Today’s route</span><strong>7</strong><small>Deliveries queued</small></div><div className="card metric"><span>On-time rate</span><strong>96%</strong><small>Last 30 days</small></div><div className="card metric"><span>Next drop</span><strong style={{fontSize:18}}>2:30 PM</strong><small>Neha Kapoor · ORD-1021</small></div><div className="card metric"><span>Delivery fee</span><strong>₹20</strong><small>Default for local orders</small></div></div><div className="kanban">{Object.entries(deliveryColumns).map(([column, cards]) => <div className="kanban-col" key={column}><div className="kanban-col-head"><span>{column}</span><span className="count">{cards.length}</span></div>{cards.map(card => <div className="delivery-card" key={card.id}><strong>{card.id} · {card.customer}</strong><small><Icon name="truck" size={11}/> {card.time} · {card.items}</small><div className="delivery-card-foot"><span>{card.amount}</span><span><Icon name="more" size={13}/></span></div></div>)}</div>)}</div></>
}

function BillingPage() {
  return <><PageHeader eyebrow="Bill-ready orders" title="Billing" subtitle="Preview, print or send a clear bill after confirmation." actions={<><Button variant="ghost" icon="search">Find order</Button><Button icon="send">Send latest bill</Button></>}/><div className="invoice-layout"><section className="card invoice-preview"><div className="invoice-brand"><div><h2>Shree Ganesh Kirana</h2><p>12 Market Lane · Pune · +91 98765 00000</p></div><div className="invoice-number"><b>ORDER #ORD-1024</b><span>02 Oct 2026 · 10:42 AM</span></div></div><div style={{padding:'17px 0',fontSize:11}}><b>Bill to</b><div style={{color:'var(--muted)',marginTop:5}}>Rahul Sharma · +91 98765 42110</div><div style={{color:'var(--muted)',marginTop:3}}>Delivery · Tomorrow morning</div></div><table className="invoice-table"><thead><tr><th>Item</th><th>Qty</th><th>Price</th></tr></thead><tbody>{[['Aashirvaad Atta 2kg','1','₹120'],['Sugar 500g','1','₹30'],['Amul Butter 100g','1','₹60'],['Fortune Sunflower Oil 1L','1','₹145']].map(row=><tr key={row[0]}><td><b>{row[0]}</b></td><td>{row[1]}</td><td>{row[2]}</td></tr>)}</tbody></table><div className="invoice-total"><div><span>Subtotal</span><b>₹355</b></div><div><span>Delivery</span><b>₹20</b></div><div className="total"><span>Total</span><b>₹375</b></div></div><div className="card-actions" style={{justifyContent:'flex-end'}}><Button variant="ghost">Print</Button><Button variant="ai" icon="send">Send on WhatsApp</Button></div></section><section className="card activity"><div className="section-head"><div><h2>WhatsApp updates</h2><p>Activity for ORD-1024</p></div><span className="source-pill">Connected</span></div>{[['Order received','10:42 AM'],['AI clarification sent','10:43 AM'],['Customer responded','10:49 AM'],['Order confirmed','10:51 AM'],['Bill sent','Not yet'],['Packing','Waiting'],['Out for delivery','Waiting']].map(([item,time],i)=><div className="activity-item" key={item}><div className={`activity-icon ${i>3?'pending':''}`}><Icon name={i>3?'more':'check'} size={12}/></div><div><strong>{item}</strong><span>{time}</span></div></div>)}</section></div></>
}

function AnalyticsPage() {
  return <><PageHeader eyebrow="Store intelligence" title="Analytics" subtitle="Small signals that help you stock and serve better." actions={<Button variant="ghost">This week ▾</Button>}/><div className="metric-row"><div className="card metric"><span>Today’s orders</span><strong>24</strong><small>+12% vs yesterday</small></div><div className="card metric"><span>Revenue</span><strong>₹8,450</strong><small>+8.4% vs yesterday</small></div><div className="card metric"><span>Average order</span><strong>₹352</strong><small>+4.1% this week</small></div><div className="card metric"><span>WhatsApp share</span><strong>68%</strong><small>16 of 24 orders</small></div></div><div className="grid two-col"><section className="card chart-card"><div className="section-head"><div><h2>Revenue trend</h2><p>Orders by day, in ₹ thousands.</p></div></div><div className="chart" style={{height:220}}>{[38,48,42,64,59,82,71,92,74,88,78,98].map((height,i)=><div className={`bar ${i===11?'accent':''}`} style={{height:`${height}%`}} key={i}/>)}</div><div className="chart-labels"><span>23 Sep</span><span>25 Sep</span><span>27 Sep</span><span>29 Sep</span><span>02 Oct</span></div></section><section className="card section-card"><div className="section-head"><div><h2>Order sources</h2><p>How customers reach your store.</p></div></div><div style={{display:'grid',placeItems:'center',height:158}}><div style={{width:145,height:145,borderRadius:'50%',background:'conic-gradient(var(--sage) 0 68%, var(--orange) 68% 92%, var(--lavender) 92% 100%)',display:'grid',placeItems:'center'}}><div style={{width:92,height:92,borderRadius:'50%',background:'#fff',display:'grid',placeItems:'center',textAlign:'center'}}><strong style={{fontFamily:'Manrope',fontSize:20}}>24</strong><span style={{fontSize:10,color:'var(--muted)'}}>orders</span></div></div></div><div className="mini-list"><div className="mini-list-row"><span><i style={{display:'inline-block',width:7,height:7,borderRadius:'50%',background:'var(--sage)',marginRight:7}}/>WhatsApp</span><b>68%</b></div><div className="mini-list-row"><span><i style={{display:'inline-block',width:7,height:7,borderRadius:'50%',background:'var(--orange)',marginRight:7}}/>Physical shop</span><b>24%</b></div><div className="mini-list-row"><span><i style={{display:'inline-block',width:7,height:7,borderRadius:'50%',background:'var(--lavender)',marginRight:7}}/>Other</span><b>8%</b></div></div></section></div></>
}

function SettingsPage() {
  return <><PageHeader eyebrow="Workspace preferences" title="Settings" subtitle="Keep the store profile and AI guardrails up to date."/><div className="grid two-col"><section className="card section-card"><div className="section-head"><div><h2>Store profile</h2><p>Shown on bills and delivery notes.</p></div></div>{[['Store name','Shree Ganesh Kirana'],['Phone number','+91 98765 00000'],['Address','12 Market Lane, Pune']].map(([label,value])=><div key={label} style={{marginBottom:14}}><label className="field-label">{label}</label><input className="input" defaultValue={value}/></div>)}<Button>Save changes</Button></section><section className="card section-card"><div className="section-head"><div><h2>AI order guardrails</h2><p>How GullyCart should behave when details are missing.</p></div></div>{[['Ask before guessing','Always clarify low-confidence products'],['Check stock before confirm','Prevent selling unavailable products'],['Suggest WhatsApp replies','Draft short, friendly messages']].map(([label,desc],i)=><div key={label} style={{display:'flex',justifyContent:'space-between',alignItems:'center',gap:12,padding:'13px 0',borderBottom:'1px solid var(--line)'}}><div><strong style={{display:'block',fontSize:12}}>{label}</strong><span style={{display:'block',fontSize:10,color:'var(--muted)',marginTop:4}}>{desc}</span></div><div style={{width:35,height:20,borderRadius:20,background:i===1?'var(--sage)':'var(--sage)',padding:3}}><div style={{width:14,height:14,borderRadius:'50%',background:'#fff',marginLeft:'auto'}}/></div></div>)}</section></div></>
}

export default function Operations({ page }) {
  const pages = {orders:<OrdersPage/>,clarifications:<ClarificationsPage/>,products:<ProductsPage/>,inventory:<ProductsPage inventory/>,customers:<CustomersPage/>,deliveries:<DeliveriesPage/>,billing:<BillingPage/>,analytics:<AnalyticsPage/>,settings:<SettingsPage/>}
  return pages[page] || <OrdersPage/>
}
