import { useNavigate } from 'react-router-dom'
import { Icon, Button, PageHeader, StatusBadge } from '../components/ui'
import { dashboardOrders, products } from '../data/mockData'

function StatCard({ label, value, foot, icon, accent }) {
  return <div className="card kpi-card" style={accent ? {'--sage-soft': accent} : undefined}><div className="kpi-top"><span>{label}</span><i className="kpi-icon"><Icon name={icon} size={15}/></i></div><div className="kpi-value">{value}</div><div className="kpi-foot">{foot}</div></div>
}

function OrderTable({ compact = false }) {
  const rows = compact ? dashboardOrders.slice(0, 4) : dashboardOrders
  return <div className="table-wrap"><table className="orders-table"><thead><tr><th>Order</th><th>Customer</th><th>Source</th><th>Items</th><th>Amount</th><th>Delivery</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(order => <tr key={order.id}><td><span className="order-id">{order.id}</span></td><td><div className="customer-cell"><strong>{order.customer}</strong><span>{order.phone}</span></div></td><td>{order.source}</td><td>{order.items}</td><td><strong>{order.amount}</strong></td><td>{order.delivery}</td><td><StatusBadge status={order.status}/></td><td><button className="icon-btn"><Icon name="more" size={15}/></button></td></tr>)}</tbody></table></div>
}

export default function Overview() {
  const navigate = useNavigate()
  return <>
    <PageHeader eyebrow="Wednesday, 02 October 2026" title="Good morning, Arjun" subtitle="Here’s what’s happening at your store today." actions={<><Button variant="ghost" icon="search">Search</Button><Button icon="plus" onClick={() => navigate('/ai-desk')}>New order</Button></>}/>
    <div className="grid kpi-grid"><StatCard label="Today's orders" value="24" foot={<><span className="trend">+12%</span> vs yesterday</>} icon="bag"/><StatCard label="Pending clarifications" value="5" foot="Needs your attention" icon="help"/><StatCard label="Today's revenue" value="₹8,450" foot={<><span className="trend">+8.4%</span> vs yesterday</>} icon="chart"/><StatCard label="Out for delivery" value="7" foot="3 arriving before 5 PM" icon="truck"/><StatCard label="Low stock items" value="12" foot="Across 6 categories" icon="warehouse"/></div>
    <div className="grid two-col">
      <section className="card section-card"><div className="section-head"><div><h2>AI attention needed</h2><p>Orders where your review will unblock the next step.</p></div><button className="text-link" onClick={() => navigate('/clarifications')}>View all <Icon name="arrow" size={12}/></button></div><div className="attention-card"><div className="attention-head"><div className="attention-customer"><div className="avatar">RS</div><div><h3>Rahul Sharma</h3><p>Order ORD-1024 · 2 min ago</p></div></div><span className="source-pill">WhatsApp</span></div><div className="quote">“2 kilo atta aur tel bhi dena”</div><div className="ai-result"><div><strong>Aashirvaad Atta · 2kg</strong><span>Matched with your catalogue</span></div><div className="confidence">97%<div className="progress"><i style={{width:'97%'}}/></div></div></div><div className="ai-result"><div><strong>Oil</strong><span>Type and pack size missing</span></div><div className="confidence low">42%<div className="progress"><i className="low" style={{width:'42%'}}/></div></div></div><div className="attention-foot"><Button variant="ai" onClick={() => navigate('/ai-desk')}>Review order</Button><Button variant="ghost" onClick={() => navigate('/clarifications')}>Send clarification</Button></div></div></section>
      <section className="card chart-card"><div className="section-head"><div><h2>Orders this week</h2><p>Steady growth from WhatsApp orders.</p></div><span className="source-pill" style={{background:'var(--sage-soft)',color:'var(--sage-dark)'}}>24 today</span></div><div className="chart">{[45,62,52,77,66,88,72].map((height,i) => <div className={`bar ${i===5 ? 'accent' : ''}`} style={{height:`${height}%`}} key={i}/>)}</div><div className="chart-labels"><span>Mon</span><span>Tue</span><span>Wed</span><span>Thu</span><span>Fri</span><span>Sat</span><span>Sun</span></div><div className="divider"/><div className="section-head" style={{marginBottom:12}}><div><h2>Popular today</h2></div><button className="text-link" onClick={() => navigate('/analytics')}>Analytics <Icon name="arrow" size={12}/></button></div><div className="mini-list"><div className="mini-list-row"><div className="mini-product"><div className="product-thumb">A</div><div><strong>Aashirvaad Atta</strong><span>18 orders today</span></div></div><b>₹2,160</b></div><div className="mini-list-row"><div className="mini-product"><div className="product-thumb green">S</div><div><strong>Sugar</strong><span>14 orders today</span></div></div><b>₹672</b></div><div className="mini-list-row"><div className="mini-product"><div className="product-thumb lavender">O</div><div><strong>Sunflower Oil</strong><span>11 orders today</span></div></div><b>₹1,595</b></div></div></section>
    </div>
    <section className="card section-card" style={{marginTop:17}}><div className="section-head"><div><h2>Recent orders</h2><p>Orders from WhatsApp and your physical counter.</p></div><button className="text-link" onClick={() => navigate('/orders')}>See all orders <Icon name="arrow" size={12}/></button></div><OrderTable compact/></section>
  </>
}
